### ISSUE TITLE
Provide Help

### ISSUE THREAD

**Issue by jqueguiner** [oscar-corpus/oscar-website#4]
Hi, 
I'd like to provide help by :

1. hosting the files on ovh object storage
2. hosting splitted version of the datasets with chunks of 500MB
3. Encode those chunk with BPE and sentence piece
4. Host the encoded version on object storage

**Comment by jqueguiner** [comment]
hi I am basically training GPT-2 on all languages using OSCAR if you are interested :  https://watch-me-learn-to-talk.com
I build polyglot on top of OSCAR and GPT-2-Simple: 
https://github.com/jqueguiner/polyglot

**Comment by pjox** [comment]
Hello,

I just answered your e-mail concerning the storage (sorry for the delay). I'm extremely interested by this polyglot GPT-2, if you need the unshuffled versions of OSCAR (that might be better suited for this) and want to open source the models, please let me know. And sorry again for the delay.
